# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['pysrc/server.py'],
             pathex=['/Users/tom/Desktop/Tesis/TesisFlaskBackend'],
             binaries=[],
             datas=[],
             hiddenimports=[
                'joblib.parallel_backend',
                            'scipy.special.cython_special',
                            'sklearn.externals.joblib',
                            'sklearn.utils.sparsetools._graph_validation',
                            'sklearn.utils.sparsetools._graph_tools',
                            'sklearn.utils.lgamma',
                            'sklearn.utils.weight_vector',
                            'sklearn.utils.fixes',
                            'sklearn.utils.extmath',
                            'sklearn.metrics.ranking',                         
                            'sklearn.neighbors.typedefs',                            
                            'sklearn.utils._cython_blas',                              
                            'sklearn.neighbors.quad_tree', 
                            'sklearn.tree._utils',
                            'sklearn.utils.parallel_backend',
                            'engineio.async_eventlet',
                            'engineio.async_threading',                            
                            'engineio.async_gevent',   
                            'engineio.async_drivers.gevent',  
                            'engineio.async_drivers.eventlet',       
                            'engineio.async_drivers.threading',                      
                            'eventlet.hubs.epolls',
                            'eventlet.hubs.kqueue',
                            'eventlet.hubs.poll',
                            'eventlet.hubs.selects',
                            'threading',                         
                            'dns.dnssec',
                            'dns.e164',
                            'dns.edns',
                            'dns.entropy',
                            'dns.exception',
                            'dns.flags',
                            'dns.grange',
                            'dns.hash',
                            'dns.inet',
                            'dns.ipv4',
                            'dns.ipv6',
                            'dns.message',
                            'dns.name',
                            'dns.namedict',
                            'dns.node',
                            'dns.opcode',
                            'dns.query',
                            'dns.rcode',
                            'dns.rdata',
                            'dns.rdataclass',
                            'dns.rdataset',
                            'dns.rdatatype',
                            'dns.renderer',
                            'dns.resolver',
                            'dns.reversename',
                            'dns.rrset',
                            'dns.set',
                            'dns.tokenizer',
                            'dns.tsig',
                            'dns.tsigkeyring',
                            'dns.ttl',
                            'dns.update',
                            'dns.version',
                            'dns.wiredata',
                            'dns.zone',

                           'dns.asyncbackend',
                           'dns.asyncquery',
                           'dns.asyncresolver'
             ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='server',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='server')
